#!/usr/bin/env python3
from __future__ import annotations

def render_table(rows, headers):
    col_widths = [len(h) for h in headers]
    for row in rows:
        for idx, key in enumerate(headers):
            col_widths[idx] = max(col_widths[idx], len(row.get(key, "")))
    def fmt_row(row):
        return "| " + " | ".join(
            row.get(h, "").ljust(col_widths[i]) for i, h in enumerate(headers)
        ) + " |"
    header_line = fmt_row({h: h for h in headers})
    sep_line = "| " + " | ".join("-" * w for w in col_widths) + " |"
    body = "\n".join(fmt_row(r) for r in rows)
    return "\n".join([header_line, sep_line, body])

def main():
    headers = [
        "Connector",
        "Venue",
        "Feature flags",
        "Market data",
        "Account",
        "Execution",
        "Cancel all",
        "Trade modes",
        "Multi-connector",
        "CLI/env selection",
        "Notes",
    ]
    rows = [
        {
            "Connector": "mock",
            "Venue": "Mock",
            "Feature flags": "none",
            "Market data": "Yes (synthetic L2 snapshots)",
            "Account": "No",
            "Execution": "No (ShadowAckAdapter only)",
            "Cancel all": "No",
            "Trade modes": "Shadow, Paper",
            "Multi-connector": "No (single connector per run)",
            "CLI/env selection": "--connector mock | PARAPHINA_LIVE_CONNECTOR=mock",
            "Notes": "Market data generated by live binary; no account/REST wiring.",
        },
        {
            "Connector": "hyperliquid",
            "Venue": "Hyperliquid",
            "Feature flags": "live_hyperliquid",
            "Market data": "Yes (public WS)",
            "Account": "Yes (polling + private WS when enabled)",
            "Execution": "Yes (REST place/cancel)",
            "Cancel all": "No (not implemented)",
            "Trade modes": "Shadow, Paper, Testnet, Live",
            "Multi-connector": "No (single connector per run)",
            "CLI/env selection": "--connector hyperliquid | PARAPHINA_LIVE_CONNECTOR=hyperliquid",
            "Notes": "Account needs HL_VAULT_ADDRESS; private WS needs HL_PRIVATE_KEY.",
        },
        {
            "Connector": "hyperliquid_fixture",
            "Venue": "Hyperliquid (fixture)",
            "Feature flags": "live_hyperliquid",
            "Market data": "Yes (fixture feed)",
            "Account": "Yes (account fixture feed)",
            "Execution": "No (exec client not wired)",
            "Cancel all": "No",
            "Trade modes": "Shadow, Paper",
            "Multi-connector": "No (single connector per run)",
            "CLI/env selection": "--connector hyperliquid_fixture | PARAPHINA_LIVE_CONNECTOR=hyperliquid_fixture",
            "Notes": "Offline replay only; uses HL_FIXTURE_DIR.",
        },
        {
            "Connector": "lighter",
            "Venue": "Lighter",
            "Feature flags": "live_lighter",
            "Market data": "Yes (public WS)",
            "Account": "Conditional (polling only when non-shadow + not paper)",
            "Execution": "Yes (REST; paper mode suppresses sending)",
            "Cancel all": "Yes",
            "Trade modes": "Shadow, Paper, Testnet, Live",
            "Multi-connector": "No (single connector per run)",
            "CLI/env selection": "--connector lighter | PARAPHINA_LIVE_CONNECTOR=lighter",
            "Notes": "Private WS exists but not wired by live binary.",
        },
        {
            "Connector": "extended",
            "Venue": "Extended",
            "Feature flags": "n/a (missing connector impl)",
            "Market data": "No (missing connector impl)",
            "Account": "No (missing connector impl)",
            "Execution": "No (missing connector impl)",
            "Cancel all": "No",
            "Trade modes": "n/a",
            "Multi-connector": "No (single connector per run)",
            "CLI/env selection": "--connector extended | PARAPHINA_LIVE_CONNECTOR=extended",
            "Notes": "Roadmap-B venue; connector stub only.",
        },
        {
            "Connector": "aster",
            "Venue": "Aster",
            "Feature flags": "n/a (missing connector impl)",
            "Market data": "No (missing connector impl)",
            "Account": "No (missing connector impl)",
            "Execution": "No (missing connector impl)",
            "Cancel all": "No",
            "Trade modes": "n/a",
            "Multi-connector": "No (single connector per run)",
            "CLI/env selection": "--connector aster | PARAPHINA_LIVE_CONNECTOR=aster",
            "Notes": "Roadmap-B venue; connector stub only.",
        },
        {
            "Connector": "paradex",
            "Venue": "Paradex",
            "Feature flags": "n/a (missing connector impl)",
            "Market data": "No (missing connector impl)",
            "Account": "No (missing connector impl)",
            "Execution": "No (missing connector impl)",
            "Cancel all": "No",
            "Trade modes": "n/a",
            "Multi-connector": "No (single connector per run)",
            "CLI/env selection": "--connector paradex | PARAPHINA_LIVE_CONNECTOR=paradex",
            "Notes": "Roadmap-B venue; connector stub only.",
        },
    ]
    print(render_table(rows, headers))

if __name__ == "__main__":
    main()
